import type { Metadata } from "next";
import {Poppins, Anton} from "next/font/google"
import "./globals.css";
import NavBar from "./components/NavBar";



const PoppinsSans = Poppins({
  variable: "--font-poppins-sans",
  subsets:["latin"],
  weight: ["100" , "200", "300" , "400", "500", "600", "700"]
})



const anton = Anton({
  subsets: ["latin"],
  weight: "400", // só existe esse peso, mas já é bold
  variable: "--font-anton",
});


export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
     <body className={`${PoppinsSans.variable} ${anton.variable} antialiased`}>

          <NavBar/>
        {children}
      </body>
    </html>
  );
}
