import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";



const PoppinsSans = Poppins({
  variable: "--font-poppins-sans",
  subsets:["latin"],
  weight: ["100", "200", "300"]
})


export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${PoppinsSans.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
